apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: o4d-noted
  name: service-binding-operator-postgresql-access
rules:
- apiGroups: ["postgresql.baiju.dev"]
  resources: ["databases"]
  verbs: ["get"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  namespace: o4d-noted
  name: service-binding-operator-postgresql-binding
subjects:
- kind: ServiceAccount
  name: service-binding-operator
  namespace: openshift-operators
roleRef:
  kind: Role
  name: service-binding-operator-postgresql-access
  apiGroup: rbac.authorization.k8s.io